name: deploy to common

on:
  workflow_run:
    workflows: ["build"]
    branches:
      - common
    types:
      - completed

permissions:
  actions: read   # Allows read access to artifacts and other workflow resources
  contents: read 
  
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "common"
      branch: "common"
      runid: ${{ github.event.workflow_run.id }}