name: Deploy-Test

on:
  workflow_run:
    workflows: ["Build-Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: List artifact files
        run: ls -l